# Generated by Django 5.2.5 on 2026-10-04 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('cout_sous_stockage', models.DecimalField(decimal_places=2, default=50.0, help_text='Marge perdue + impact santé (C_u)', max_digits=10)),
                ('cout_surstockage', models.DecimalField(decimal_places=2, default=10.0, help_text="Prix d'achat + stockage + risque (C_o)", max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Réception Fournisseur'), ('SORTIE', 'Vente Client')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('impact_financier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='GedGedPharma.medicament')),
            ],
        ),
    ]
